apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  #type: ClusterIP - default (not reachable from outside), NodePort, LoadBalancer
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80