apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: khyulian/kube-demo-frontend:latest
          env:
            - name: AUTH_ADDRESS
              #value: "10.105.142.246"
              # serviceName.nameSpace
              value: "auth-service.default"